#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_NPC_015_Guide_Analyst

#include "Basic.hpp"

#include "AnimBP_NpcBase_structs.hpp"


namespace SDK
{

// ScriptStruct AnimBP_NPC_015_Guide_Analyst.AnimBP_NPC_015_Guide_Analyst_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x00F8 - 0x00F8)
struct AnimBP_NPC_015_Guide_Analyst::FAnimBlueprintGeneratedConstantData final : public AnimBP_NpcBase::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(AnimBP_NPC_015_Guide_Analyst::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on AnimBP_NPC_015_Guide_Analyst::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(AnimBP_NPC_015_Guide_Analyst::FAnimBlueprintGeneratedConstantData) == 0x0000F8, "Wrong size on AnimBP_NPC_015_Guide_Analyst::FAnimBlueprintGeneratedConstantData");

}

