#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_NPC_015_Guide_Damaged

#include "Basic.hpp"

#include "AnimBP_NpcBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_NPC_015_Guide_Damaged.AnimBP_NPC_015_Guide_Damaged_C
// 0x0000 (0x0970 - 0x0970)
class UAnimBP_NPC_015_Guide_Damaged_C final : public UAnimBP_NpcBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBP_NPC_015_Guide_Damaged_C">();
	}
	static class UAnimBP_NPC_015_Guide_Damaged_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_NPC_015_Guide_Damaged_C>();
	}
};
static_assert(alignof(UAnimBP_NPC_015_Guide_Damaged_C) == 0x000010, "Wrong alignment on UAnimBP_NPC_015_Guide_Damaged_C");
static_assert(sizeof(UAnimBP_NPC_015_Guide_Damaged_C) == 0x000970, "Wrong size on UAnimBP_NPC_015_Guide_Damaged_C");

}

