#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AOE_Blair_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function AOE_Blair_Base.AOE_Blair_Base_C.ExecuteUbergraph_AOE_Blair_Base
// 0x0080 (0x0080 - 0x0000)
struct AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityContextHandle                CallFunc_GetAbilityContextHandle_ReturnValue;      // 0x0008(0x0010)(ConstParm)
	class AActor*                                 CallFunc_AbilityContextGetInstigator_ReturnValue;  // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABlair_C*                               K2Node_DynamicCast_AsBlair;                        // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABlair_C*                               K2Node_DynamicCast_AsBlair_1;                      // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x003C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityId                           CallFunc_InvokeFirstStatusEffectToTargetByTag_ReturnValue; // 0x0060(0x0010)(HasGetValueTypeHash)
	double                                        CallFunc_UpdateDestConsumingLoc_Alpha_ImplicitCast; // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetLifeSpan_InLifespan_ImplicitCast;      // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base");
static_assert(sizeof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base) == 0x000080, "Wrong size on AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, EntryPoint) == 0x000000, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::EntryPoint' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_IsDedicatedServer_ReturnValue) == 0x000004, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x000005, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_GetAbilityContextHandle_ReturnValue) == 0x000008, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_GetAbilityContextHandle_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_AbilityContextGetInstigator_ReturnValue) == 0x000018, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_AbilityContextGetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, K2Node_DynamicCast_AsBlair) == 0x000020, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::K2Node_DynamicCast_AsBlair' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, K2Node_DynamicCast_AsBlair_1) == 0x000030, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::K2Node_DynamicCast_AsBlair_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x00003C, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_GetInstigator_ReturnValue) == 0x000048, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_IsValid_ReturnValue) == 0x000050, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_GetInstigator_ReturnValue_1) == 0x000058, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_GetInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_InvokeFirstStatusEffectToTargetByTag_ReturnValue) == 0x000060, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_InvokeFirstStatusEffectToTargetByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_UpdateDestConsumingLoc_Alpha_ImplicitCast) == 0x000070, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_UpdateDestConsumingLoc_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base, CallFunc_SetLifeSpan_InLifespan_ImplicitCast) == 0x000078, "Member 'AOE_Blair_Base_C_ExecuteUbergraph_AOE_Blair_Base::CallFunc_SetLifeSpan_InLifespan_ImplicitCast' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.FadeOutLoopFXs
// 0x0020 (0x0020 - 0x0000)
struct AOE_Blair_Base_C_FadeOutLoopFXs final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_FadeOutLoopFXs) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_FadeOutLoopFXs");
static_assert(sizeof(AOE_Blair_Base_C_FadeOutLoopFXs) == 0x000020, "Wrong size on AOE_Blair_Base_C_FadeOutLoopFXs");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, Temp_int_Array_Index_Variable) == 0x000000, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, CallFunc_Array_Length_ReturnValue) == 0x00000C, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, CallFunc_Array_Get_Item) == 0x000010, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, CallFunc_Less_IntInt_ReturnValue) == 0x000018, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_FadeOutLoopFXs, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'AOE_Blair_Base_C_FadeOutLoopFXs::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.InitializeFxParams
// 0x0018 (0x0018 - 0x0000)
struct AOE_Blair_Base_C_InitializeFxParams final
{
public:
	double                                        CallFunc_GetDecalSize_OutSize;                     // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetDecalSize_OutSize_1;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetFloatParameter_Param_ImplicitCast;     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetFloatParameter_Param_ImplicitCast_1;   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_InitializeFxParams) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_InitializeFxParams");
static_assert(sizeof(AOE_Blair_Base_C_InitializeFxParams) == 0x000018, "Wrong size on AOE_Blair_Base_C_InitializeFxParams");
static_assert(offsetof(AOE_Blair_Base_C_InitializeFxParams, CallFunc_GetDecalSize_OutSize) == 0x000000, "Member 'AOE_Blair_Base_C_InitializeFxParams::CallFunc_GetDecalSize_OutSize' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_InitializeFxParams, CallFunc_GetDecalSize_OutSize_1) == 0x000008, "Member 'AOE_Blair_Base_C_InitializeFxParams::CallFunc_GetDecalSize_OutSize_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_InitializeFxParams, CallFunc_SetFloatParameter_Param_ImplicitCast) == 0x000010, "Member 'AOE_Blair_Base_C_InitializeFxParams::CallFunc_SetFloatParameter_Param_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_InitializeFxParams, CallFunc_SetFloatParameter_Param_ImplicitCast_1) == 0x000014, "Member 'AOE_Blair_Base_C_InitializeFxParams::CallFunc_SetFloatParameter_Param_ImplicitCast_1' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.PlayProjectileAkEvent
// 0x0028 (0x0028 - 0x0000)
struct AOE_Blair_Base_C_PlayProjectileAkEvent final
{
public:
	bool                                          bSpawnOrDestroy;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EValidOutputPin                               CallFunc_FindAkComponentWithValid_OutputPins;      // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AkComponent*                         CallFunc_FindAkComponentWithValid_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EValidOutputPin                               CallFunc_FindAkComponentWithValid_OutputPins_1;    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AkComponent*                         CallFunc_FindAkComponentWithValid_ReturnValue_1;   // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_PlayProjectileAkEvent) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_PlayProjectileAkEvent");
static_assert(sizeof(AOE_Blair_Base_C_PlayProjectileAkEvent) == 0x000028, "Wrong size on AOE_Blair_Base_C_PlayProjectileAkEvent");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, bSpawnOrDestroy) == 0x000000, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::bSpawnOrDestroy' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_IsValid_ReturnValue_1) == 0x000002, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_FindAkComponentWithValid_OutputPins) == 0x000003, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_FindAkComponentWithValid_OutputPins' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_FindAkComponentWithValid_ReturnValue) == 0x000008, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_FindAkComponentWithValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, K2Node_SwitchEnum_CmpSuccess) == 0x000010, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_FindAkComponentWithValid_OutputPins_1) == 0x000011, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_FindAkComponentWithValid_OutputPins_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_FindAkComponentWithValid_ReturnValue_1) == 0x000018, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_FindAkComponentWithValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_IsValid_ReturnValue_2) == 0x000020, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000021, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_PlayProjectileAkEvent, K2Node_SwitchEnum_CmpSuccess_1) == 0x000022, "Member 'AOE_Blair_Base_C_PlayProjectileAkEvent::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.SpawnLoopFXs
// 0x0048 (0x0048 - 0x0000)
struct AOE_Blair_Base_C_SpawnLoopFXs final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GetDecalSize_OutSize;                     // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UNiagaraComponent*>              CallFunc_SpawnFXsForAbility_ReturnValue;           // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	float                                         CallFunc_SetFloatParameter_Param_ImplicitCast;     // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetFloatParameter_Param_ImplicitCast_1;   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_SpawnLoopFXs) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_SpawnLoopFXs");
static_assert(sizeof(AOE_Blair_Base_C_SpawnLoopFXs) == 0x000048, "Wrong size on AOE_Blair_Base_C_SpawnLoopFXs");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, Temp_int_Array_Index_Variable) == 0x000000, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_GetDecalSize_OutSize) == 0x000010, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_GetDecalSize_OutSize' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_Array_Get_Item) == 0x000018, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_Less_IntInt_ReturnValue) == 0x000024, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000028, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_SpawnFXsForAbility_ReturnValue) == 0x000030, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_SpawnFXsForAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_SetFloatParameter_Param_ImplicitCast) == 0x000040, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_SetFloatParameter_Param_ImplicitCast' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnLoopFXs, CallFunc_SetFloatParameter_Param_ImplicitCast_1) == 0x000044, "Member 'AOE_Blair_Base_C_SpawnLoopFXs::CallFunc_SetFloatParameter_Param_ImplicitCast_1' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.SpawnUniqueEndFx
// 0x0070 (0x0070 - 0x0000)
struct AOE_Blair_Base_C_SpawnUniqueEndFx final
{
public:
	bool                                          FxAlreadyAttached;                                 // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAttached_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue_1;        // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           K2Node_MakeArray_Array;                            // 0x0040(0x0010)(ReferenceParm)
	TArray<class USceneComponent*>                CallFunc_GetChildrenComponents_Children;           // 0x0050(0x0010)(ReferenceParm, ContainsInstancedReference)
	class USceneComponent*                        CallFunc_Array_Get_Item;                           // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ComponentHasTag_ReturnValue;              // 0x006D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_SpawnUniqueEndFx) == 0x000008, "Wrong alignment on AOE_Blair_Base_C_SpawnUniqueEndFx");
static_assert(sizeof(AOE_Blair_Base_C_SpawnUniqueEndFx) == 0x000070, "Wrong size on AOE_Blair_Base_C_SpawnUniqueEndFx");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, FxAlreadyAttached) == 0x000000, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::FxAlreadyAttached' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_GetInstigator_ReturnValue) == 0x000010, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_K2_GetRootComponent_ReturnValue) == 0x000018, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_K2_GetRootComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_SpawnSystemAttached_ReturnValue) == 0x000020, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_SpawnSystemAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_GetInstigator_ReturnValue_1) == 0x000030, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_GetInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_K2_GetRootComponent_ReturnValue_1) == 0x000038, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_K2_GetRootComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, K2Node_MakeArray_Array) == 0x000040, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_GetChildrenComponents_Children) == 0x000050, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_GetChildrenComponents_Children' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_Array_Get_Item) == 0x000060, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_Array_Length_ReturnValue) == 0x000068, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_SpawnUniqueEndFx, CallFunc_ComponentHasTag_ReturnValue) == 0x00006D, "Member 'AOE_Blair_Base_C_SpawnUniqueEndFx::CallFunc_ComponentHasTag_ReturnValue' has a wrong offset!");

// Function AOE_Blair_Base.AOE_Blair_Base_C.UpdateDestConsumingLoc
// 0x0160 (0x0160 - 0x0000)
struct AOE_Blair_Base_C_UpdateDestConsumingLoc final
{
public:
	double                                        Alpha;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CurveOffset;                                       // 0x0008(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               LookAtRot;                                         // 0x0014(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	class APawn*                                  DestActor;                                         // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GreaterGreater_VectorRotator_ReturnValue; // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0xC];                                       // 0x0044(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0050(0x0030)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_TransformLocation_ReturnValue;            // 0x0080(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x008C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0098(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x00B0(0x009C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14D[0x3];                                      // 0x014D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x0150(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_VLerp_Alpha_ImplicitCast;                 // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AOE_Blair_Base_C_UpdateDestConsumingLoc) == 0x000010, "Wrong alignment on AOE_Blair_Base_C_UpdateDestConsumingLoc");
static_assert(sizeof(AOE_Blair_Base_C_UpdateDestConsumingLoc) == 0x000160, "Wrong size on AOE_Blair_Base_C_UpdateDestConsumingLoc");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, Alpha) == 0x000000, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::Alpha' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CurveOffset) == 0x000008, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CurveOffset' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, LookAtRot) == 0x000014, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::LookAtRot' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, DestActor) == 0x000020, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::DestActor' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_IsDedicatedServer_ReturnValue) == 0x000028, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00002C, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_GreaterGreater_VectorRotator_ReturnValue) == 0x000038, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_GreaterGreater_VectorRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_GetTransform_ReturnValue) == 0x000050, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_TransformLocation_ReturnValue) == 0x000080, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_TransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_VLerp_ReturnValue) == 0x00008C, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_Add_VectorVector_ReturnValue) == 0x000098, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_GetInstigator_ReturnValue) == 0x0000A8, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x0000B0, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_IsValid_ReturnValue) == 0x00014C, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_FindLookAtRotation_ReturnValue) == 0x000150, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AOE_Blair_Base_C_UpdateDestConsumingLoc, CallFunc_VLerp_Alpha_ImplicitCast) == 0x00015C, "Member 'AOE_Blair_Base_C_UpdateDestConsumingLoc::CallFunc_VLerp_Alpha_ImplicitCast' has a wrong offset!");

}

