#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AR_1006

#include "Basic.hpp"

#include "AR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AR_1006.AR_1006_C
// 0x0000 (0x1C80 - 0x1C80)
class UAR_1006_C final : public UAR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AR_1006_C">();
	}
	static class UAR_1006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAR_1006_C>();
	}
};
static_assert(alignof(UAR_1006_C) == 0x000010, "Wrong alignment on UAR_1006_C");
static_assert(sizeof(UAR_1006_C) == 0x001C80, "Wrong size on UAR_1006_C");

}

