#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StarryNight2

#include "Basic.hpp"

#include "BP_StarryNight2_classes.hpp"
#include "BP_StarryNight2_parameters.hpp"


namespace SDK
{

// Function BP_StarryNight2.BP_StarryNight2_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_StarryNight2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StarryNight2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StarryNight2.BP_StarryNight2_C.OnOpacityChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   NewOpacity                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StarryNight2_C::OnOpacityChanged(float NewOpacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StarryNight2_C", "OnOpacityChanged");

	Params::BP_StarryNight2_C_OnOpacityChanged Parms{};

	Parms.NewOpacity = NewOpacity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StarryNight2.BP_StarryNight2_C.ExecuteUbergraph_BP_StarryNight2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StarryNight2_C::ExecuteUbergraph_BP_StarryNight2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StarryNight2_C", "ExecuteUbergraph_BP_StarryNight2");

	Params::BP_StarryNight2_C_ExecuteUbergraph_BP_StarryNight2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StarryNight2.BP_StarryNight2_C.CreateMID
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_StarryNight2_C::CreateMID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StarryNight2_C", "CreateMID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StarryNight2.BP_StarryNight2_C.ApplyMaterialParameters
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewOpacity                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StarryNight2_C::ApplyMaterialParameters(double NewOpacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StarryNight2_C", "ApplyMaterialParameters");

	Params::BP_StarryNight2_C_ApplyMaterialParameters Parms{};

	Parms.NewOpacity = NewOpacity;

	UObject::ProcessEvent(Func, &Parms);
}

}

