#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BR_1001

#include "Basic.hpp"

#include "BR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass BR_1001.BR_1001_C
// 0x0000 (0x1C80 - 0x1C80)
class UBR_1001_C final : public UBR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BR_1001_C">();
	}
	static class UBR_1001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBR_1001_C>();
	}
};
static_assert(alignof(UBR_1001_C) == 0x000010, "Wrong alignment on UBR_1001_C");
static_assert(sizeof(UBR_1001_C) == 0x001C80, "Wrong size on UBR_1001_C");

}

