#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_AR_1001

#include "Basic.hpp"

#include "F_AR_structs.hpp"


namespace SDK
{

// ScriptStruct F_AR_1001.F_AR_1001_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct F_AR_1001::FAnimBlueprintGeneratedConstantData final : public F_AR::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(F_AR_1001::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on F_AR_1001::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(F_AR_1001::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on F_AR_1001::FAnimBlueprintGeneratedConstantData");

}

