#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_HC_1002

#include "Basic.hpp"

#include "F_HC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_HC_1002.F_HC_1002_C
// 0x0000 (0x1C80 - 0x1C80)
class UF_HC_1002_C final : public UF_HC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_HC_1002_C">();
	}
	static class UF_HC_1002_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_HC_1002_C>();
	}
};
static_assert(alignof(UF_HC_1002_C) == 0x000010, "Wrong alignment on UF_HC_1002_C");
static_assert(sizeof(UF_HC_1002_C) == 0x001C80, "Wrong size on UF_HC_1002_C");

}

