#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_LNC_1005

#include "Basic.hpp"

#include "F_LNC_structs.hpp"


namespace SDK
{

// ScriptStruct F_LNC_1005.F_LNC_1005_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct F_LNC_1005::FAnimBlueprintGeneratedConstantData final : public F_LNC::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(F_LNC_1005::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on F_LNC_1005::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(F_LNC_1005::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on F_LNC_1005::FAnimBlueprintGeneratedConstantData");

}

