#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HC_1008

#include "Basic.hpp"

#include "HC_structs.hpp"


namespace SDK
{

// ScriptStruct HC_1008.HC_1008_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct HC_1008::FAnimBlueprintGeneratedConstantData final : public HC::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(HC_1008::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on HC_1008::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(HC_1008::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on HC_1008::FAnimBlueprintGeneratedConstantData");

}

