#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HC_1001_0

#include "Basic.hpp"

#include "HC_structs.hpp"


namespace SDK
{

// ScriptStruct HC_1001.HC_1001_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct HC_1001_0::FAnimBlueprintGeneratedConstantData final : public HC::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(HC_1001_0::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on HC_1001_0::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(HC_1001_0::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on HC_1001_0::FAnimBlueprintGeneratedConstantData");

}

