#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HC

#include "Basic.hpp"

#include "UpperBody_structs.hpp"


namespace SDK
{

// ScriptStruct HC.HC_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct HC::FAnimBlueprintGeneratedConstantData : public UpperBody::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(HC::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on HC::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(HC::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on HC::FAnimBlueprintGeneratedConstantData");

}

