#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1005

#include "Basic.hpp"

#include "LNC_structs.hpp"


namespace SDK
{

// ScriptStruct LNC_1005.LNC_1005_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct LNC_1005::FAnimBlueprintGeneratedConstantData final : public LNC::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(LNC_1005::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on LNC_1005::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(LNC_1005::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on LNC_1005::FAnimBlueprintGeneratedConstantData");

}

