#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1004_0

#include "Basic.hpp"

#include "LNC_structs.hpp"


namespace SDK
{

// ScriptStruct LNC_1004.LNC_1004_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct LNC_1004_0::FAnimBlueprintGeneratedConstantData final : public LNC::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(LNC_1004_0::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on LNC_1004_0::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(LNC_1004_0::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on LNC_1004_0::FAnimBlueprintGeneratedConstantData");

}

