#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNC_1005

#include "Basic.hpp"

#include "LNC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass LNC_1005.LNC_1005_C
// 0x0000 (0x1C80 - 0x1C80)
class ULNC_1005_C final : public ULNC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNC_1005_C">();
	}
	static class ULNC_1005_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULNC_1005_C>();
	}
};
static_assert(alignof(ULNC_1005_C) == 0x000010, "Wrong alignment on ULNC_1005_C");
static_assert(sizeof(ULNC_1005_C) == 0x001C80, "Wrong size on ULNC_1005_C");

}

