#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LNCTamedbeastProjectile

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LNCTamedbeastProjectile.LNCTamedbeastProjectile_C
// 0x0000 (0x0BA0 - 0x0BA0)
class ALNCTamedbeastProjectile_C final : public AM1AbilityProjectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LNCTamedbeastProjectile_C">();
	}
	static class ALNCTamedbeastProjectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALNCTamedbeastProjectile_C>();
	}
};
static_assert(alignof(ALNCTamedbeastProjectile_C) == 0x000008, "Wrong alignment on ALNCTamedbeastProjectile_C");
static_assert(sizeof(ALNCTamedbeastProjectile_C) == 0x000BA0, "Wrong size on ALNCTamedbeastProjectile_C");

}

