#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MAGSpawnedNiagaraComponents

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct MAGSpawnedNiagaraComponents.MAGSpawnedNiagaraComponents
// 0x0010 (0x0010 - 0x0000)
struct FMAGSpawnedNiagaraComponents final
{
public:
	TArray<class UNiagaraComponent*>              Comps_6_4CF3696244A45ACF8091AE9F51A84D86;          // 0x0000(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
};
static_assert(alignof(FMAGSpawnedNiagaraComponents) == 0x000008, "Wrong alignment on FMAGSpawnedNiagaraComponents");
static_assert(sizeof(FMAGSpawnedNiagaraComponents) == 0x000010, "Wrong size on FMAGSpawnedNiagaraComponents");
static_assert(offsetof(FMAGSpawnedNiagaraComponents, Comps_6_4CF3696244A45ACF8091AE9F51A84D86) == 0x000000, "Member 'FMAGSpawnedNiagaraComponents::Comps_6_4CF3696244A45ACF8091AE9F51A84D86' has a wrong offset!");

}

