#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MG_1006

#include "Basic.hpp"

#include "MG_structs.hpp"


namespace SDK
{

// ScriptStruct MG_1006.MG_1006_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct MG_1006::FAnimBlueprintGeneratedConstantData final : public MG::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(MG_1006::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on MG_1006::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(MG_1006::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on MG_1006::FAnimBlueprintGeneratedConstantData");

}

