#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_005_PortalDevice

#include "Basic.hpp"

#include "NPC_005_PortalDevice_classes.hpp"
#include "NPC_005_PortalDevice_parameters.hpp"


namespace SDK
{

// Function NPC_005_PortalDevice.NPC_005_PortalDevice_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_005_PortalDevice_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_005_PortalDevice_C", "ReceiveTick");

	Params::NPC_005_PortalDevice_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_005_PortalDevice.NPC_005_PortalDevice_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_005_PortalDevice_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_005_PortalDevice_C", "ReceiveActorBeginOverlap");

	Params::NPC_005_PortalDevice_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_005_PortalDevice.NPC_005_PortalDevice_C.ExecuteUbergraph_NPC_005_PortalDevice
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_005_PortalDevice_C::ExecuteUbergraph_NPC_005_PortalDevice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_005_PortalDevice_C", "ExecuteUbergraph_NPC_005_PortalDevice");

	Params::NPC_005_PortalDevice_C_ExecuteUbergraph_NPC_005_PortalDevice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_005_PortalDevice.NPC_005_PortalDevice_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_005_PortalDevice_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_005_PortalDevice_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

