#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_015_Guide_IronHeart

#include "Basic.hpp"

#include "NPC_015_Guide_IronHeart_classes.hpp"
#include "NPC_015_Guide_IronHeart_parameters.hpp"


namespace SDK
{

// Function NPC_015_Guide_IronHeart.NPC_015_Guide_IronHeart_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_015_Guide_IronHeart_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_015_Guide_IronHeart_C", "ReceiveTick");

	Params::NPC_015_Guide_IronHeart_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_015_Guide_IronHeart.NPC_015_Guide_IronHeart_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_015_Guide_IronHeart_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_015_Guide_IronHeart_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_015_Guide_IronHeart.NPC_015_Guide_IronHeart_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_015_Guide_IronHeart_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_015_Guide_IronHeart_C", "ReceiveActorBeginOverlap");

	Params::NPC_015_Guide_IronHeart_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_015_Guide_IronHeart.NPC_015_Guide_IronHeart_C.ExecuteUbergraph_NPC_015_Guide_IronHeart
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_015_Guide_IronHeart_C::ExecuteUbergraph_NPC_015_Guide_IronHeart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_015_Guide_IronHeart_C", "ExecuteUbergraph_NPC_015_Guide_IronHeart");

	Params::NPC_015_Guide_IronHeart_C_ExecuteUbergraph_NPC_015_Guide_IronHeart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

