#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_001_Alpha

#include "Basic.hpp"

#include "NPC_001_Alpha_classes.hpp"
#include "NPC_001_Alpha_parameters.hpp"


namespace SDK
{

// Function NPC_001_Alpha.NPC_001_Alpha_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_001_Alpha_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_001_Alpha_C", "ReceiveTick");

	Params::NPC_001_Alpha_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_001_Alpha.NPC_001_Alpha_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_001_Alpha_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_001_Alpha_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_001_Alpha.NPC_001_Alpha_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_001_Alpha_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_001_Alpha_C", "ReceiveActorBeginOverlap");

	Params::NPC_001_Alpha_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_001_Alpha.NPC_001_Alpha_C.ExecuteUbergraph_NPC_001_Alpha
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_001_Alpha_C::ExecuteUbergraph_NPC_001_Alpha(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_001_Alpha_C", "ExecuteUbergraph_NPC_001_Alpha");

	Params::NPC_001_Alpha_C_ExecuteUbergraph_NPC_001_Alpha Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

