#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_042_AlbionOperator_A

#include "Basic.hpp"

#include "NPC_042_AlbionOperator_A_classes.hpp"
#include "NPC_042_AlbionOperator_A_parameters.hpp"


namespace SDK
{

// Function NPC_042_AlbionOperator_A.NPC_042_AlbionOperator_A_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_042_AlbionOperator_A_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_042_AlbionOperator_A_C", "ReceiveTick");

	Params::NPC_042_AlbionOperator_A_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_042_AlbionOperator_A.NPC_042_AlbionOperator_A_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_042_AlbionOperator_A_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_042_AlbionOperator_A_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_042_AlbionOperator_A.NPC_042_AlbionOperator_A_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_042_AlbionOperator_A_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_042_AlbionOperator_A_C", "ReceiveActorBeginOverlap");

	Params::NPC_042_AlbionOperator_A_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_042_AlbionOperator_A.NPC_042_AlbionOperator_A_C.ExecuteUbergraph_NPC_042_AlbionOperator_A
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_042_AlbionOperator_A_C::ExecuteUbergraph_NPC_042_AlbionOperator_A(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_042_AlbionOperator_A_C", "ExecuteUbergraph_NPC_042_AlbionOperator_A");

	Params::NPC_042_AlbionOperator_A_C_ExecuteUbergraph_NPC_042_AlbionOperator_A Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

