#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_036_InstanceDungeondevice

#include "Basic.hpp"

#include "NPC_036_InstanceDungeondevice_classes.hpp"
#include "NPC_036_InstanceDungeondevice_parameters.hpp"


namespace SDK
{

// Function NPC_036_InstanceDungeondevice.NPC_036_InstanceDungeondevice_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_036_InstanceDungeondevice_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_036_InstanceDungeondevice_C", "ReceiveTick");

	Params::NPC_036_InstanceDungeondevice_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_036_InstanceDungeondevice.NPC_036_InstanceDungeondevice_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_036_InstanceDungeondevice_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_036_InstanceDungeondevice_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_036_InstanceDungeondevice.NPC_036_InstanceDungeondevice_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_036_InstanceDungeondevice_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_036_InstanceDungeondevice_C", "ReceiveActorBeginOverlap");

	Params::NPC_036_InstanceDungeondevice_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_036_InstanceDungeondevice.NPC_036_InstanceDungeondevice_C.ExecuteUbergraph_NPC_036_InstanceDungeondevice
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_036_InstanceDungeondevice_C::ExecuteUbergraph_NPC_036_InstanceDungeondevice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_036_InstanceDungeondevice_C", "ExecuteUbergraph_NPC_036_InstanceDungeondevice");

	Params::NPC_036_InstanceDungeondevice_C_ExecuteUbergraph_NPC_036_InstanceDungeondevice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

