#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_22_SigvoresProof

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PerkAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PerkAbility_22_SigvoresProof.PerkAbility_22_SigvoresProof_C
// 0x0010 (0x02D8 - 0x02C8)
class UPerkAbility_22_SigvoresProof_C final : public UPerkAbilityBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PerkAbility_22_SigvoresProof_C;     // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   AltProjectileDataRowName;                          // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_PerkAbility_22_SigvoresProof(int32 EntryPoint);
	void OnAbilityEvent_E33ED40D43EC049C54B0CC82EED11105(const struct FM1AbilityEvent& Event);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PerkAbility_22_SigvoresProof_C">();
	}
	static class UPerkAbility_22_SigvoresProof_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerkAbility_22_SigvoresProof_C>();
	}
};
static_assert(alignof(UPerkAbility_22_SigvoresProof_C) == 0x000008, "Wrong alignment on UPerkAbility_22_SigvoresProof_C");
static_assert(sizeof(UPerkAbility_22_SigvoresProof_C) == 0x0002D8, "Wrong size on UPerkAbility_22_SigvoresProof_C");
static_assert(offsetof(UPerkAbility_22_SigvoresProof_C, UberGraphFrame_PerkAbility_22_SigvoresProof_C) == 0x0002C8, "Member 'UPerkAbility_22_SigvoresProof_C::UberGraphFrame_PerkAbility_22_SigvoresProof_C' has a wrong offset!");
static_assert(offsetof(UPerkAbility_22_SigvoresProof_C, AltProjectileDataRowName) == 0x0002D0, "Member 'UPerkAbility_22_SigvoresProof_C::AltProjectileDataRowName' has a wrong offset!");

}

