#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_4_DivinePunishment

#include "Basic.hpp"

#include "PerkAbility_4_DivinePunishment_classes.hpp"
#include "PerkAbility_4_DivinePunishment_parameters.hpp"


namespace SDK
{

// Function PerkAbility_4_DivinePunishment.PerkAbility_4_DivinePunishment_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_4_DivinePunishment_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_4_DivinePunishment_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkAbility_4_DivinePunishment.PerkAbility_4_DivinePunishment_C.ExecuteUbergraph_PerkAbility_4_DivinePunishment
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_4_DivinePunishment_C::ExecuteUbergraph_PerkAbility_4_DivinePunishment(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_4_DivinePunishment_C", "ExecuteUbergraph_PerkAbility_4_DivinePunishment");

	Params::PerkAbility_4_DivinePunishment_C_ExecuteUbergraph_PerkAbility_4_DivinePunishment Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_4_DivinePunishment.PerkAbility_4_DivinePunishment_C.OnAbilityEvent_546B5C984F288B98E44199BA65A1E934
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_4_DivinePunishment_C::OnAbilityEvent_546B5C984F288B98E44199BA65A1E934(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_4_DivinePunishment_C", "OnAbilityEvent_546B5C984F288B98E44199BA65A1E934");

	Params::PerkAbility_4_DivinePunishment_C_OnAbilityEvent_546B5C984F288B98E44199BA65A1E934 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_4_DivinePunishment.PerkAbility_4_DivinePunishment_C.OnAddedSE
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UM1StatusEffect*                  StatusEffect                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_4_DivinePunishment_C::OnAddedSE(const class UM1StatusEffect* StatusEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_4_DivinePunishment_C", "OnAddedSE");

	Params::PerkAbility_4_DivinePunishment_C_OnAddedSE Parms{};

	Parms.StatusEffect = StatusEffect;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_4_DivinePunishment.PerkAbility_4_DivinePunishment_C.OnRemovedSE
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UM1StatusEffect*                  StatusEffect                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_4_DivinePunishment_C::OnRemovedSE(const class UM1StatusEffect* StatusEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_4_DivinePunishment_C", "OnRemovedSE");

	Params::PerkAbility_4_DivinePunishment_C_OnRemovedSE Parms{};

	Parms.StatusEffect = StatusEffect;

	UObject::ProcessEvent(Func, &Parms);
}

}

