#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_7_NazestrasDevotion

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PerkAbilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PerkAbility_7_NazestrasDevotion.PerkAbility_7_NazestrasDevotion_C
// 0x0008 (0x02D0 - 0x02C8)
class UPerkAbility_7_NazestrasDevotion_C final : public UPerkAbilityBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PerkAbility_7_NazestrasDevotion_C;  // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_PerkAbility_7_NazestrasDevotion(int32 EntryPoint);
	void OnAbilityEvent_DB23546B4B75BDEDCCAD38986FFB649E(const struct FM1AbilityEvent& Event);
	void OnEvent_99BD73234FC3B7231488379A1429A84E(const struct FM1CalcDamageInfo& DamageInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PerkAbility_7_NazestrasDevotion_C">();
	}
	static class UPerkAbility_7_NazestrasDevotion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerkAbility_7_NazestrasDevotion_C>();
	}
};
static_assert(alignof(UPerkAbility_7_NazestrasDevotion_C) == 0x000008, "Wrong alignment on UPerkAbility_7_NazestrasDevotion_C");
static_assert(sizeof(UPerkAbility_7_NazestrasDevotion_C) == 0x0002D0, "Wrong size on UPerkAbility_7_NazestrasDevotion_C");
static_assert(offsetof(UPerkAbility_7_NazestrasDevotion_C, UberGraphFrame_PerkAbility_7_NazestrasDevotion_C) == 0x0002C8, "Member 'UPerkAbility_7_NazestrasDevotion_C::UberGraphFrame_PerkAbility_7_NazestrasDevotion_C' has a wrong offset!");

}

