#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_8_BlueBeetle

#include "Basic.hpp"

#include "PerkAbility_8_BlueBeetle_classes.hpp"
#include "PerkAbility_8_BlueBeetle_parameters.hpp"


namespace SDK
{

// Function PerkAbility_8_BlueBeetle.PerkAbility_8_BlueBeetle_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_8_BlueBeetle_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_8_BlueBeetle_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkAbility_8_BlueBeetle.PerkAbility_8_BlueBeetle_C.ExecuteUbergraph_PerkAbility_8_BlueBeetle
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_8_BlueBeetle_C::ExecuteUbergraph_PerkAbility_8_BlueBeetle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_8_BlueBeetle_C", "ExecuteUbergraph_PerkAbility_8_BlueBeetle");

	Params::PerkAbility_8_BlueBeetle_C_ExecuteUbergraph_PerkAbility_8_BlueBeetle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_8_BlueBeetle.PerkAbility_8_BlueBeetle_C.OnAbilityEvent_03ED67594A6AE8BA33C9369987B2A3C9
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_8_BlueBeetle_C::OnAbilityEvent_03ED67594A6AE8BA33C9369987B2A3C9(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_8_BlueBeetle_C", "OnAbilityEvent_03ED67594A6AE8BA33C9369987B2A3C9");

	Params::PerkAbility_8_BlueBeetle_C_OnAbilityEvent_03ED67594A6AE8BA33C9369987B2A3C9 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}

}

