#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_22_SigvoresProof

#include "Basic.hpp"

#include "PerkAbility_22_SigvoresProof_classes.hpp"
#include "PerkAbility_22_SigvoresProof_parameters.hpp"


namespace SDK
{

// Function PerkAbility_22_SigvoresProof.PerkAbility_22_SigvoresProof_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_22_SigvoresProof_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_22_SigvoresProof_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkAbility_22_SigvoresProof.PerkAbility_22_SigvoresProof_C.ExecuteUbergraph_PerkAbility_22_SigvoresProof
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_22_SigvoresProof_C::ExecuteUbergraph_PerkAbility_22_SigvoresProof(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_22_SigvoresProof_C", "ExecuteUbergraph_PerkAbility_22_SigvoresProof");

	Params::PerkAbility_22_SigvoresProof_C_ExecuteUbergraph_PerkAbility_22_SigvoresProof Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_22_SigvoresProof.PerkAbility_22_SigvoresProof_C.OnAbilityEvent_E33ED40D43EC049C54B0CC82EED11105
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_22_SigvoresProof_C::OnAbilityEvent_E33ED40D43EC049C54B0CC82EED11105(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_22_SigvoresProof_C", "OnAbilityEvent_E33ED40D43EC049C54B0CC82EED11105");

	Params::PerkAbility_22_SigvoresProof_C_OnAbilityEvent_E33ED40D43EC049C54B0CC82EED11105 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}

}

