#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkAbility_5_GregsReversedFate

#include "Basic.hpp"

#include "PerkAbility_5_GregsReversedFate_classes.hpp"
#include "PerkAbility_5_GregsReversedFate_parameters.hpp"


namespace SDK
{

// Function PerkAbility_5_GregsReversedFate.PerkAbility_5_GregsReversedFate_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UPerkAbility_5_GregsReversedFate_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_5_GregsReversedFate_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkAbility_5_GregsReversedFate.PerkAbility_5_GregsReversedFate_C.ExecuteUbergraph_PerkAbility_5_GregsReversedFate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkAbility_5_GregsReversedFate_C::ExecuteUbergraph_PerkAbility_5_GregsReversedFate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_5_GregsReversedFate_C", "ExecuteUbergraph_PerkAbility_5_GregsReversedFate");

	Params::PerkAbility_5_GregsReversedFate_C_ExecuteUbergraph_PerkAbility_5_GregsReversedFate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_5_GregsReversedFate.PerkAbility_5_GregsReversedFate_C.OnAbilityEvent_A4AF1C234C2ABC0B47BAECBC0EB89862
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPerkAbility_5_GregsReversedFate_C::OnAbilityEvent_A4AF1C234C2ABC0B47BAECBC0EB89862(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_5_GregsReversedFate_C", "OnAbilityEvent_A4AF1C234C2ABC0B47BAECBC0EB89862");

	Params::PerkAbility_5_GregsReversedFate_C_OnAbilityEvent_A4AF1C234C2ABC0B47BAECBC0EB89862 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkAbility_5_GregsReversedFate.PerkAbility_5_GregsReversedFate_C.OnEvent_CA9FEB6E49AA70D866B7E187F933698F
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1CalcDamageInfo                DamageInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UPerkAbility_5_GregsReversedFate_C::OnEvent_CA9FEB6E49AA70D866B7E187F933698F(const struct FM1CalcDamageInfo& DamageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkAbility_5_GregsReversedFate_C", "OnEvent_CA9FEB6E49AA70D866B7E187F933698F");

	Params::PerkAbility_5_GregsReversedFate_C_OnEvent_CA9FEB6E49AA70D866B7E187F933698F Parms{};

	Parms.DamageInfo = std::move(DamageInfo);

	UObject::ProcessEvent(Func, &Parms);
}

}

