#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SetOptionAbility_Devourer

#include "Basic.hpp"

#include "SetOptionAbility_Devourer_classes.hpp"
#include "SetOptionAbility_Devourer_parameters.hpp"


namespace SDK
{

// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USetOptionAbility_Devourer_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Devourer_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "BP_OnDeactivated");

	Params::SetOptionAbility_Devourer_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.ExecuteUbergraph_SetOptionAbility_Devourer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Devourer_C::ExecuteUbergraph_SetOptionAbility_Devourer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "ExecuteUbergraph_SetOptionAbility_Devourer");

	Params::SetOptionAbility_Devourer_C_ExecuteUbergraph_SetOptionAbility_Devourer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.IsWeaponDamage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FM1AbilityEventDataHandle        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Devourer_C::IsWeaponDamage(const struct FM1AbilityEventDataHandle& EventData, bool* bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "IsWeaponDamage");

	Params::SetOptionAbility_Devourer_C_IsWeaponDamage Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);

	if (bResult != nullptr)
		*bResult = Parms.bResult;
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.MakeHPRatioOpParam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FM1AbilityOperationParam         OpParam                                                (Parm, OutParm, ContainsInstancedReference)

void USetOptionAbility_Devourer_C::MakeHPRatioOpParam(struct FM1AbilityOperationParam* OpParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "MakeHPRatioOpParam");

	Params::SetOptionAbility_Devourer_C_MakeHPRatioOpParam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OpParam != nullptr)
		*OpParam = std::move(Parms.OpParam);
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.OnChange_6368A3514F8AD1BF1BFB47AA81018F48
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1ScaledInteger                 Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Devourer_C::OnChange_6368A3514F8AD1BF1BFB47AA81018F48(const struct FM1ScaledInteger& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "OnChange_6368A3514F8AD1BF1BFB47AA81018F48");

	Params::SetOptionAbility_Devourer_C_OnChange_6368A3514F8AD1BF1BFB47AA81018F48 Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SetOptionAbility_Devourer.SetOptionAbility_Devourer_C.OnChange_F1D56B70417645B28F194BBB094FE818
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1ScaledInteger                 Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Devourer_C::OnChange_F1D56B70417645B28F194BBB094FE818(const struct FM1ScaledInteger& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Devourer_C", "OnChange_F1D56B70417645B28F194BBB094FE818");

	Params::SetOptionAbility_Devourer_C_OnChange_F1D56B70417645B28F194BBB094FE818 Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}

}

