#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SetOptionAbility_Pyromaniac

#include "Basic.hpp"

#include "SetOptionAbility_Pyromaniac_classes.hpp"
#include "SetOptionAbility_Pyromaniac_parameters.hpp"


namespace SDK
{

// Function SetOptionAbility_Pyromaniac.SetOptionAbility_Pyromaniac_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USetOptionAbility_Pyromaniac_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Pyromaniac_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SetOptionAbility_Pyromaniac.SetOptionAbility_Pyromaniac_C.ExecuteUbergraph_SetOptionAbility_Pyromaniac
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Pyromaniac_C::ExecuteUbergraph_SetOptionAbility_Pyromaniac(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Pyromaniac_C", "ExecuteUbergraph_SetOptionAbility_Pyromaniac");

	Params::SetOptionAbility_Pyromaniac_C_ExecuteUbergraph_SetOptionAbility_Pyromaniac Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SetOptionAbility_Pyromaniac.SetOptionAbility_Pyromaniac_C.IsKillCranedTarget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEventDataHandle        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetOptionAbility_Pyromaniac_C::IsKillCranedTarget(const struct FM1AbilityEventDataHandle& EventData, bool* bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Pyromaniac_C", "IsKillCranedTarget");

	Params::SetOptionAbility_Pyromaniac_C_IsKillCranedTarget Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);

	if (bResult != nullptr)
		*bResult = Parms.bResult;
}


// Function SetOptionAbility_Pyromaniac.SetOptionAbility_Pyromaniac_C.MakeRecoveryMpRatioOpParam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FM1AbilityOperationParam         OpParam                                                (Parm, OutParm, ContainsInstancedReference)

void USetOptionAbility_Pyromaniac_C::MakeRecoveryMpRatioOpParam(struct FM1AbilityOperationParam* OpParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Pyromaniac_C", "MakeRecoveryMpRatioOpParam");

	Params::SetOptionAbility_Pyromaniac_C_MakeRecoveryMpRatioOpParam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OpParam != nullptr)
		*OpParam = std::move(Parms.OpParam);
}


// Function SetOptionAbility_Pyromaniac.SetOptionAbility_Pyromaniac_C.OnAbilityEvent_7297682D4EB99C35EB68A5A93FEDA7F1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USetOptionAbility_Pyromaniac_C::OnAbilityEvent_7297682D4EB99C35EB68A5A93FEDA7F1(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SetOptionAbility_Pyromaniac_C", "OnAbilityEvent_7297682D4EB99C35EB68A5A93FEDA7F1");

	Params::SetOptionAbility_Pyromaniac_C_OnAbilityEvent_7297682D4EB99C35EB68A5A93FEDA7F1 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}

}

