#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_1002

#include "Basic.hpp"

#include "SG_structs.hpp"


namespace SDK
{

// ScriptStruct SG_1002.SG_1002_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct SG_1002::FAnimBlueprintGeneratedConstantData final : public SG::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(SG_1002::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on SG_1002::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(SG_1002::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on SG_1002::FAnimBlueprintGeneratedConstantData");

}

