#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_1002_0

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SG_1002.SG_1002_C
// 0x0010 (0x0470 - 0x0460)
class ASG_1002_C final : public AM1Weapon
{
public:
	class UM1WeaponRoundsReloadComponent*         M1WeaponRoundsReload;                              // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponInstantHitComponent*           M1WeaponInstantHit;                                // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SG_1002_C">();
	}
	static class ASG_1002_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASG_1002_C>();
	}
};
static_assert(alignof(ASG_1002_C) == 0x000008, "Wrong alignment on ASG_1002_C");
static_assert(sizeof(ASG_1002_C) == 0x000470, "Wrong size on ASG_1002_C");
static_assert(offsetof(ASG_1002_C, M1WeaponRoundsReload) == 0x000460, "Member 'ASG_1002_C::M1WeaponRoundsReload' has a wrong offset!");
static_assert(offsetof(ASG_1002_C, M1WeaponInstantHit) == 0x000468, "Member 'ASG_1002_C::M1WeaponInstantHit' has a wrong offset!");

}

