#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sharen

#include "Basic.hpp"

#include "PlayerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sharen.Sharen_C
// 0x0000 (0x10D0 - 0x10D0)
class ASharen_C final : public APlayerBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sharen_C">();
	}
	static class ASharen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASharen_C>();
	}
};
static_assert(alignof(ASharen_C) == 0x000010, "Wrong alignment on ASharen_C");
static_assert(sizeof(ASharen_C) == 0x0010D0, "Wrong size on ASharen_C");

}

