#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMG_1005

#include "Basic.hpp"

#include "SMG_structs.hpp"


namespace SDK
{

// ScriptStruct SMG_1005.SMG_1005_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct SMG_1005::FAnimBlueprintGeneratedConstantData final : public SMG::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(SMG_1005::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on SMG_1005::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(SMG_1005::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on SMG_1005::FAnimBlueprintGeneratedConstantData");

}

