#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SR_1006

#include "Basic.hpp"

#include "SR_structs.hpp"


namespace SDK
{

// ScriptStruct SR_1006.SR_1006_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct SR_1006::FAnimBlueprintGeneratedConstantData final : public SR::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(SR_1006::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on SR_1006::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(SR_1006::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on SR_1006::FAnimBlueprintGeneratedConstantData");

}

