#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TR_1006

#include "Basic.hpp"

#include "TR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass TR_1006.TR_1006_C
// 0x0000 (0x1C80 - 0x1C80)
class UTR_1006_C final : public UTR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TR_1006_C">();
	}
	static class UTR_1006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTR_1006_C>();
	}
};
static_assert(alignof(UTR_1006_C) == 0x000010, "Wrong alignment on UTR_1006_C");
static_assert(sizeof(UTR_1006_C) == 0x001C80, "Wrong size on UTR_1006_C");

}

