#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair_003_Middle

#include "Basic.hpp"

#include "UI_Crosshair_003_Middle_classes.hpp"
#include "UI_Crosshair_003_Middle_parameters.hpp"


namespace SDK
{

// Function UI_Crosshair_003_Middle.UI_Crosshair_003_Middle_C.ExecuteUbergraph_UI_Crosshair_003_Middle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_003_Middle_C::ExecuteUbergraph_UI_Crosshair_003_Middle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_003_Middle_C", "ExecuteUbergraph_UI_Crosshair_003_Middle");

	Params::UI_Crosshair_003_Middle_C_ExecuteUbergraph_UI_Crosshair_003_Middle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair_003_Middle.UI_Crosshair_003_Middle_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_003_Middle_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_003_Middle_C", "PreConstruct");

	Params::UI_Crosshair_003_Middle_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

