#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_InvasionDungeon_TimeAttack

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.BP_GetTimeAttackItems
// 0x0020 (0x0020 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems final
{
public:
	TArray<class UM1UIInvasionDungeonScoreItem*>  ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
	TArray<class UM1UIInvasionDungeonScoreItem*>  K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems) == 0x000008, "Wrong alignment on UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems");
static_assert(sizeof(UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems) == 0x000020, "Wrong size on UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems");
static_assert(offsetof(UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems, ReturnValue) == 0x000000, "Member 'UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems, K2Node_MakeArray_Array) == 0x000010, "Member 'UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems::K2Node_MakeArray_Array' has a wrong offset!");

}

