#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Valby

#include "Basic.hpp"

#include "PhysicsCore_structs.hpp"
#include "PlayerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Valby.Valby_C
// 0x0010 (0x10E0 - 0x10D0)
class AValby_C : public APlayerBase_C
{
public:
	TArray<EPhysicalSurface>                      ConditionSurfaces;                                 // 0x10C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	bool IsStepOnWetForLocal();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Valby_C">();
	}
	static class AValby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AValby_C>();
	}
};
static_assert(alignof(AValby_C) == 0x000010, "Wrong alignment on AValby_C");
static_assert(sizeof(AValby_C) == 0x0010E0, "Wrong size on AValby_C");
static_assert(offsetof(AValby_C, ConditionSurfaces) == 0x0010C8, "Member 'AValby_C::ConditionSurfaces' has a wrong offset!");

}

